/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labsync.labsync;

/**
 *
 * @author aleja
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo_labsync_no_background.png")).getImage());
    }
    
    // LÓGICA DE ENCRIPTACION CONTRASEÑA
    // Método para encriptar la contraseña ingresada en el Login
    private String encriptarPassword(String password) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder(2 * hash.length);
            
            for (int i = 0; i < hash.length; i++) {
                String hex = Integer.toHexString(0xff & hash[i]);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new RuntimeException("Error al encriptar: No se encontró el algoritmo SHA-256", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVerde = new javax.swing.JPanel();
        imgUTJ = new javax.swing.JLabel();
        lbLabSync = new javax.swing.JLabel();
        lbSlogan = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        panelBlanco = new javax.swing.JPanel();
        lbMatricula = new java.awt.Label();
        lbPassword = new java.awt.Label();
        password = new java.awt.TextField();
        matricula = new java.awt.TextField();
        imgLabSync = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LabSync");
        setResizable(false);

        panelVerde.setBackground(new java.awt.Color(8, 173, 141));
        panelVerde.setMinimumSize(new java.awt.Dimension(400, 500));

        imgUTJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UTJ_blanco_vertical.png"))); // NOI18N

        lbLabSync.setBackground(new java.awt.Color(0, 0, 0));
        lbLabSync.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbLabSync.setForeground(new java.awt.Color(255, 255, 255));
        lbLabSync.setText("LabSync");

        lbSlogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lbSlogan.setText("Acceso inteligente para espacios inteligentes");

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(8, 173, 141));
        btnRegister.setText("Registro");
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setFocusPainted(false);
        btnRegister.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        javax.swing.GroupLayout panelVerdeLayout = new javax.swing.GroupLayout(panelVerde);
        panelVerde.setLayout(panelVerdeLayout);
        panelVerdeLayout.setHorizontalGroup(
            panelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerdeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgUTJ)
                .addGap(121, 121, 121))
            .addGroup(panelVerdeLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lbLabSync)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelVerdeLayout.createSequentialGroup()
                .addGroup(panelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerdeLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lbSlogan))
                    .addGroup(panelVerdeLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnRegister)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelVerdeLayout.setVerticalGroup(
            panelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerdeLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgUTJ, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbLabSync)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSlogan)
                .addGap(29, 29, 29)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setMinimumSize(new java.awt.Dimension(400, 500));
        panelBlanco.setPreferredSize(new java.awt.Dimension(400, 500));

        lbMatricula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbMatricula.setText("Correo Electrónico");

        lbPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPassword.setText("Contraseña");

        password.setEchoChar('*');
        password.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        password.setName("password"); // NOI18N
        password.addActionListener(this::passwordActionPerformed);

        matricula.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        matricula.setName("matricula"); // NOI18N
        matricula.addActionListener(this::matriculaActionPerformed);

        imgLabSync.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/labsync_200.png"))); // NOI18N

        btnLogin.setBackground(new java.awt.Color(8, 173, 141));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(imgLabSync, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBlancoLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lbMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLabSync, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    /*
        BOTON DE INICIO DE SESIÓN
        AQUI IRA LA LOGICA PARA EL INICIO DE SESION YA CONECTADA CON LA BD
    */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String correo = matricula.getText().trim();
        String passwordStr = this.password.getText().trim();
        
        if (correo.isEmpty() || passwordStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Por favor, completa ambos campos para ingresar",
                "Campos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );  
            return;
        }

        String passwordEncriptada = encriptarPassword(passwordStr);
        java.sql.Connection con = ConexionBD.conectar();
        
        if (con != null) {
            try {
                String sql = "SELECT id, nombre, rol FROM usuario WHERE correo = ? AND password = ?";
                java.sql.PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, correo);
                ps.setString(2, passwordEncriptada);

                java.sql.ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    int idUsuario = rs.getInt("id");
                    String strNombre = rs.getString("nombre");
                    String rolUsuario = rs.getString("rol").trim();
                    
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "¡Bienvenido a LabSync, " + strNombre + "!",
                        "Acceso Concedido",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );
                    
                    switch (rolUsuario) {
                        case "Estudiante":
                            DashboardAlumno ventanaAlumno = new DashboardAlumno(idUsuario, strNombre);
                            ventanaAlumno.setLocationRelativeTo(null);
                            ventanaAlumno.setVisible(true);
                            this.dispose();
                        break;
                        
                        case "Profesor":
                            javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "INTERFAZ PROFESOR",
                                "Redirección de Rol",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE
                            );
                        break;
                        
                        case "Laboratorista":                            
                            DashboardLabo ventanaLabo = new DashboardLabo(strNombre);
                            ventanaLabo.setVisible(true);
                            this.dispose();
                            ventanaLabo.setLocationRelativeTo(null);
                        break;
                        
                        case "Externo":
                            javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "INTERFAZ EXTERNO",
                                "Redirección de Rol",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE
                            );
                        break;
                        
                        default:
                            javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Error en el rol asignado",
                                "Error de Permisos",
                                javax.swing.JOptionPane.ERROR_MESSAGE
                            );
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "El correo electrónico o la contraseña son incorrectas",
                        "Error de Autenticación",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error en el proceso: " + e.getMessage(),
                    "Error SQL",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            } finally {
                try {
                    con.close();
                } catch (java.sql.SQLException ex) {}
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "No hay conexión con la BD",
                "Error de red",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    // BOTON DE INICIAR SESIÓN -> REGISTO 
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        Register ventanaRegister = new Register();
        
        ventanaRegister.setVisible(true);
        this.dispose();
        ventanaRegister.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel imgLabSync;
    private javax.swing.JLabel imgUTJ;
    private javax.swing.JLabel lbLabSync;
    private java.awt.Label lbMatricula;
    private java.awt.Label lbPassword;
    private javax.swing.JLabel lbSlogan;
    private java.awt.TextField matricula;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelVerde;
    private java.awt.TextField password;
    // End of variables declaration//GEN-END:variables
}
