package labsync.labsync;

import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo_labsync_no_background.png")).getImage());
    }
    
    // FUNCION PARA HASHEAR LA CONTRASEÑA
    private String encriptarPassword(String password) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder(2 * hash.length);
            
            for (int i = 0; i < hash.length; i++) {
                String hex = Integer.toHexString(0xff & hash[i]);
                
                if (hex.length() == 1) {
                    hexString.append("0");
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new RuntimeException("Error al encriptar: No se encontro el algoritmo SH-256", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBlanco = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        nombre = new java.awt.TextField();
        lbApellidoP = new javax.swing.JLabel();
        apellidoP = new java.awt.TextField();
        lbApallidoM = new javax.swing.JLabel();
        apellidoM = new java.awt.TextField();
        lbEmail = new javax.swing.JLabel();
        email = new java.awt.TextField();
        lbRol = new javax.swing.JLabel();
        password = new java.awt.TextField();
        btnRegister = new javax.swing.JButton();
        lbPassword1 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        panelVerde = new javax.swing.JPanel();
        imgUTJ = new javax.swing.JLabel();
        lbLabSync = new javax.swing.JLabel();
        lbSolgan = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setResizable(false);

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setPreferredSize(new java.awt.Dimension(442, 415));

        lbNombre.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("Nombre");

        nombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nombre.setName("nombre"); // NOI18N
        nombre.addActionListener(this::nombreActionPerformed);

        lbApellidoP.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lbApellidoP.setForeground(new java.awt.Color(0, 0, 0));
        lbApellidoP.setText("Apellido Paterno");

        apellidoP.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        apellidoP.setName("apellidoP"); // NOI18N
        apellidoP.addActionListener(this::apellidoPActionPerformed);

        lbApallidoM.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lbApallidoM.setForeground(new java.awt.Color(0, 0, 0));
        lbApallidoM.setText("Apellido Materno");

        apellidoM.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        apellidoM.setName("apellidoM"); // NOI18N
        apellidoM.addActionListener(this::apellidoMActionPerformed);

        lbEmail.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(0, 0, 0));
        lbEmail.setText("Correo Electrónico");

        email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        email.setName("correo"); // NOI18N
        email.addActionListener(this::emailActionPerformed);

        lbRol.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lbRol.setForeground(new java.awt.Color(0, 0, 0));
        lbRol.setText("¿Cuál es tu rol?");

        password.setEchoChar('*');
        password.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        password.setName("password"); // NOI18N
        password.addActionListener(this::passwordActionPerformed);

        btnRegister.setBackground(new java.awt.Color(8, 173, 141));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrarse");
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setFocusPainted(false);
        btnRegister.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        lbPassword1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lbPassword1.setForeground(new java.awt.Color(0, 0, 0));
        lbPassword1.setText("Contraseña");

        rol.setBackground(new java.awt.Color(255, 255, 255));
        rol.setForeground(new java.awt.Color(51, 51, 51));
        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor", "Laboratorista", "Externo" }));
        rol.setSelectedIndex(-1);
        rol.setName("rol"); // NOI18N

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lbNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBlancoLayout.createSequentialGroup()
                                .addComponent(lbApallidoM)
                                .addGap(36, 36, 36))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addComponent(lbApellidoP)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addComponent(lbPassword1)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbRol)
                            .addComponent(btnRegister))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                        .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbNombre)
                .addGap(1, 1, 1)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbApellidoP)
                .addGap(1, 1, 1)
                .addComponent(apellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbApallidoM)
                .addGap(1, 1, 1)
                .addComponent(apellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmail)
                .addGap(1, 1, 1)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPassword1)
                .addGap(1, 1, 1)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panelVerde.setBackground(new java.awt.Color(8, 173, 141));
        panelVerde.setForeground(new java.awt.Color(255, 255, 255));

        imgUTJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UTJ_blanco_vertical.png"))); // NOI18N

        lbLabSync.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbLabSync.setForeground(new java.awt.Color(255, 255, 255));
        lbLabSync.setText("LabSync");

        lbSolgan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSolgan.setForeground(new java.awt.Color(255, 255, 255));
        lbSolgan.setText("Acceso inteligente para espacios inteligentes");

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(8, 173, 141));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout panelVerdeLayout = new javax.swing.GroupLayout(panelVerde);
        panelVerde.setLayout(panelVerdeLayout);
        panelVerdeLayout.setHorizontalGroup(
            panelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerdeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(imgUTJ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerdeLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(panelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerdeLayout.createSequentialGroup()
                        .addComponent(lbSolgan)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerdeLayout.createSequentialGroup()
                        .addComponent(lbLabSync)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerdeLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(133, 133, 133))))
        );
        panelVerdeLayout.setVerticalGroup(
            panelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerdeLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imgUTJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLabSync)
                .addGap(12, 12, 12)
                .addComponent(lbSolgan)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addComponent(panelVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // BOTON DE REGISTRO - INICIAR SESIÓN
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login ventanaLogin = new Login();
        
        ventanaLogin.setVisible(true);
        this.dispose();
        ventanaLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoPActionPerformed

    private void apellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoMActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /*
        AQUI IRA TODO LA LÓGICA PARA EL REGISTRO DE UN USUARIO NUEVO
        BOTON DE REGISTRO (CREAR CUENTA)
    */
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String strNombre = nombre.getText().trim();
        String strApellidoP = apellidoP.getText().trim();
        String strApellidoM = apellidoM.getText().trim();
        String strEmail = email.getText().trim();
        String strPassword = this.password.getText().trim();
        String passwordEncriptada = encriptarPassword(strPassword);
        
        // 1. VALIDAR QUE LOS CAMPOS ESTÉN COMPLETOS
        if (strNombre.isEmpty() || strApellidoP.isEmpty() || strApellidoM.isEmpty() || strEmail.isEmpty() || strPassword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. VALIDAR QUE EL COMBOBOX (ROL) ESTE SELECCIONADO
        if (rol.getSelectedIndex() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione que tipo de usuario es para continuar.", "Selección requerida", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        } 
        
        String rolSeleccionado = rol.getSelectedItem().toString().trim();
        
        // 3. VALIDAR QUE EL CORREO Y EL ROL CORRESPONDAN
        if (rolSeleccionado.equals("Estudiante")) {
            if (!strEmail.endsWith("@soy.utj.edu.mx")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Correo no válido para el rol seleccionado.", "Dominio no válido", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if (rolSeleccionado.equals("Profesor") || rolSeleccionado.equals("Laboratorista")) {
            if (!strEmail.endsWith("@utj.edu.mx")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Correo no válido para el rol seleccionado.", "Dominio no válido", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        // 4. PEDIR DATOS EXTRA CON VENTANAS EMERGENTES
        String datoExtra1 = "N/A", datoExtra2 = "N/A", datoExtra3 = "N/A";
        String[] opcionesTurno = {"Matutino", "Vespertino"};
        String[] opcionesCarrera = {"TSU - DSM", "TSU - ENV"};
        String[] opcionesPiso = {"PB - M", "1 - 5"};
        
        if (rolSeleccionado.equals("Estudiante")) {
            datoExtra1 = javax.swing.JOptionPane.showInputDialog(this, "Por favor, ingresa tu matrícula");
            if (datoExtra1 == null || datoExtra1.trim().isEmpty()) return; 
            
            datoExtra2 = (String) javax.swing.JOptionPane.showInputDialog(this, "Selecciona tu carrera: ", "Carrera", javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcionesCarrera, opcionesCarrera[0]);
            if (datoExtra2 == null) return;
            
            datoExtra3 = (String) javax.swing.JOptionPane.showInputDialog(this, "Selecciona tu turno: ", "Turno", javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcionesTurno, opcionesTurno[0]);
            if (datoExtra3 == null) return;
            
        } else if (rolSeleccionado.equals("Laboratorista")) {
            datoExtra1 = (String) javax.swing.JOptionPane.showInputDialog(this, "Selecciona tu turno: ", "Turno", javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcionesTurno, opcionesTurno[0]);
            if (datoExtra1 == null) return;
            
            datoExtra2 = (String) javax.swing.JOptionPane.showInputDialog(this, "Seleccione sus pisos encargados: ", "Piso", javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcionesPiso, opcionesPiso[0]);
            if (datoExtra2 == null) return;
            
        } else if (rolSeleccionado.equals("Externo")) { 
            datoExtra1 = javax.swing.JOptionPane.showInputDialog(this, "Por favor, ingresa tu Institución de Origen:");
            if (datoExtra1 == null || datoExtra1.trim().isEmpty()) return;
            
            datoExtra2 = javax.swing.JOptionPane.showInputDialog(this, "Por favor, ingresa el Motivo de la Visita:");
            if (datoExtra2 == null || datoExtra2.trim().isEmpty()) return;
        }
        
        // 5. REGISTRO EN LA BASE DE DATOS
        java.sql.Connection con = ConexionBD.conectar();
        if (con != null) {
            try {
                con.setAutoCommit(false);
                
                // 1. INSERCIÓN EN TABLA PADRE
                String sqlUsuario = "INSERT INTO usuario (nombre, apellido_p, apellido_m, rol, correo, password) VALUES (?, ?, ?, ?, ?, ?)";
                java.sql.PreparedStatement psUser = con.prepareStatement(sqlUsuario, java.sql.Statement.RETURN_GENERATED_KEYS);
                psUser.setString(1, strNombre);
                psUser.setString(2, strApellidoP);
                psUser.setString(3, strApellidoM);
                psUser.setString(4, rolSeleccionado);
                psUser.setString(5, strEmail);     
                psUser.setString(6, passwordEncriptada);  
                
                // Ejecutamos y verificamos cuántas filas se afectaron
                int filasAfectadas = psUser.executeUpdate();
                
                if (filasAfectadas == 0) {
                    throw new Exception("Falló la creación del usuario general, no se afectaron filas.");
                }
                
                java.sql.ResultSet rs = psUser.getGeneratedKeys();
                int idGenerado = -1;
                if (rs.next()) {
                    idGenerado = rs.getInt(1);
                } else {
                    throw new Exception("No se pudo obtener el ID autogenerado del usuario.");
                }
                
                // 2. INSERCIÓN EN TABLA HIJA
                if (idGenerado != -1) {
                    if (rolSeleccionado.equals("Estudiante")) { 
                        String sqlAlumno = "INSERT INTO estudiante (id_usuario, matricula, carrera, turno) VALUES (?, ?, ?, ?)";
                        java.sql.PreparedStatement psAlumno = con.prepareStatement(sqlAlumno);
                        psAlumno.setInt(1, idGenerado);
                        psAlumno.setString(2, datoExtra1); 
                        psAlumno.setString(3, datoExtra2); 
                        psAlumno.setString(4, datoExtra3); 
                        psAlumno.executeUpdate();
                        
                    } else if (rolSeleccionado.equals("Laboratorista")) {
                        String sqlLab = "INSERT INTO laboratorista (id_usuario, turno, piso_encargado) VALUES (?, ?, ?)";
                        java.sql.PreparedStatement psLab = con.prepareStatement(sqlLab);
                        psLab.setInt(1, idGenerado);
                        psLab.setString(2, datoExtra1); 
                        psLab.setString(3, datoExtra2); 
                        psLab.executeUpdate();
                        
                    } else if (rolSeleccionado.equals("Externo")) {
                        String sqlExterno = "INSERT INTO externo (id_usuario, institucion_origen, motivo_visita) VALUES (?, ?, ?)";
                        java.sql.PreparedStatement psExterno = con.prepareStatement(sqlExterno);
                        psExterno.setInt(1, idGenerado);
                        psExterno.setString(2, datoExtra1); 
                        psExterno.setString(3, datoExtra2); 
                        psExterno.executeUpdate();
                    }
                    
                    // Guardamos los cambios permanentemente
                    con.commit();
                    
                    // MENSAJE DE ÉXITO Y CAMBIO DE VENTANA
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Cuenta creada con éxito para " + strNombre + "!", "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                    Login ventanaLogin = new Login();
                    ventanaLogin.setVisible(true);
                    ventanaLogin.setLocationRelativeTo(null);
                    this.dispose();
                }
                
            } catch (Exception e) {
                try {
                    System.out.println("Error en transacción: " + e.getMessage());
                    e.printStackTrace(); 
                    con.rollback(); 
                } catch (java.sql.SQLException ex) {
                    System.out.println("Error al hacer rollback: " + ex.getMessage());
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar en la Base de Datos:\n" + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    con.setAutoCommit(true);
                    con.close();
                } catch (java.sql.SQLException ex) {}
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo establecer conexión con la base de datos.", "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField apellidoM;
    private java.awt.TextField apellidoP;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private java.awt.TextField email;
    private javax.swing.JLabel imgUTJ;
    private javax.swing.JLabel lbApallidoM;
    private javax.swing.JLabel lbApellidoP;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLabSync;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPassword1;
    private javax.swing.JLabel lbRol;
    private javax.swing.JLabel lbSolgan;
    private java.awt.TextField nombre;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelVerde;
    private java.awt.TextField password;
    private javax.swing.JComboBox<String> rol;
    // End of variables declaration//GEN-END:variables
}
